### ISSUE TITLE
Offer to take over the project

### ISSUE THREAD

**Issue by BlogmasterAvery** [cesare-montresor/Satisfactory_PUREXMod#8]
Just in case the issue where the mod was hidden on SMM/ficsit.app doesnt get resolved on it's own, and if you aren't going to fix it, I'd like to offer to fork the mod and republish it in a working state. I'm an experienced modder and I maintain several up to date mods of my own, and I have the time to keep them working https://ficsit.app/user/6JmYooAefnXoRy

Love the mod, it'd be a shame to lose it. Let me know if I have your permission to fork/republish.

**Comment by Fireztonez** [comment]
If you can make a fork of this mod, support it, and update it would be really nice. I love this mod and think it deserves to receive a little love from someone with the time and inclination to do it.

Look like all the source code is availiable, but I can't find the license of the project. I'm not the autor so for sure I can't confirm you have the right to do the fork.

**Comment by BlogmasterAvery** [comment]
> If you can make a fork of this mod, support it, and update it would be really nice. I love this mod and think it deserves to receive a little love from someone with the time and inclination to do it.
> 
> Look like all the source code is availiable, but I can't find the license of the project. I'm not the autor so for sure I can't confirm you have the right to do the fork.

If I get no response in the next couple days and the SML devs can't (won't?) fix it on their end, I can just remake the mod from scratch with new assets, I know that's allowed.

**Comment by BlogmasterAvery** [comment]
Never mind, looks like the SML devs fixed it on their end, so I'll close the issue. However, if it becomes outdated for real in the future I still intend to remake it if the author doesn't want to update it.
